# Generated by Django 5.2.8 on 2025-11-30 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('reservas', models.JSONField()),
                ('cantidad_pasajeros', models.PositiveIntegerField()),
                ('capacidad_origen_antes', models.IntegerField(blank=True, null=True)),
                ('capacidad_origen_despues', models.IntegerField(blank=True, null=True)),
                ('capacidad_destino_antes', models.IntegerField(blank=True, null=True)),
                ('capacidad_destino_despues', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('OK', 'Transferencia exitosa'), ('ERROR', 'Transferencia fallida')], max_length=10)),
                ('mensaje', models.TextField(blank=True)),
                ('destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_destino', to='administracion.horario')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_origen', to='administracion.horario')),
            ],
        ),
    ]
