# Generated by Django 5.2.8 on 2025-11-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_rename_propuesta_origen_negociacion_costo_por_pasajero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='transferida',
            field=models.BooleanField(default=False),
        ),
    ]
