# Generated by Django 5.2.8 on 2026-01-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_reserva_unique_asiento_por_horario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='reserva',
            name='unique_asiento_por_horario',
        ),
        migrations.AddField(
            model_name='reserva',
            name='restringida',
            field=models.BooleanField(default=False),
        ),
    ]
